//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,N1,N2,N3,N4,N5,N6
        ///12/25/82,11,18,22,28,35,37
        ///12/18/82,7,13,23,32,33,45
        ///12/11/82,4,9,10,11,43,46
        ///12/04/82,6,17,24,36,38,46
        ///11/27/82,5,17,21,28,30,43
        ///11/20/82,3,4,19,33,34,48
        ///11/13/82,4,11,23,24,25,45
        ///11/06/82,8,14,16,18,31,48
        ///10/30/82,11,18,19,31,37,45
        ///10/23/82,7,18,23,25,37,45
        ///10/16/82,11,23,25,28,29,36
        ///10/09/82,13,16,18,34,35,36
        ///10/02/82,4,14,18,40,43,44
        ///09/25/82,9,12,13,14,44,48
        ///09/18/82,8,18,36,39,41,47
        ///09/11/82,25,28,29,30,35,44
        ///09/04/82,7,14,17,20,37,47
        ///08/28/82,11,17,19,20,36,43 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LotoData {
            get {
                return ResourceManager.GetString("LotoData", resourceCulture);
            }
        }
    }
}
